/*
 *
 * Copyright (c) 2026 Renesas Electronics Corporation
 *
 * SPDX-License-Identifier: MIT
 *
 */

#ifndef __RCAR_UCIE_UCIE_PHY_H__
#define __RCAR_UCIE_UCIE_PHY_H__

#define DVSEC_BASE_ADD                RCAR_UCIE_BASE_ADD(0x00000524) // 0xc, don't use
#define DWORD_0_BASE_ADD              RCAR_UCIE_BASE_ADD(0x41f00000) // 0x300000
#define MMPL_BASE_ADD                 RCAR_UCIE_BASE_ADD(0x41f01000) // 0x301000
#define ACSM_BASE_ADD                 RCAR_UCIE_BASE_ADD(0x41f02000) // 0x302000
#define ACSMIM_BASE_ADD               RCAR_UCIE_BASE_ADD(0x41f03000) // 0x303000
#define DWORD_1_BASE_ADD              RCAR_UCIE_BASE_ADD(0x41f10000) // 0x310000

#define DVSEC_DVSECLINKCONTROL_ADD    (DVSEC_BASE_ADD + 0x4)

#define DWORD_0_DWMODECTRL0_ADD    	(DWORD_0_BASE_ADD + 0x4)
#define DWORD_0_DWPUBMODECTRL_ADD    (DWORD_0_BASE_ADD + 0x6c)
#define DWORD_0_DWVREFVAR_ADD    	(DWORD_0_BASE_ADD + 0xdc)
#define DWORD_0_DWTXZCALSB_ADD    	(DWORD_0_BASE_ADD + 0xf8)
#define DWORD_0_DWTXZCALSB_DWTXZCALNSB_MASK  0x7f
#define DWORD_0_DWTXZCALSB_DWTXZCALNSB_SHIFT 8
#define DWORD_0_DWTXZCALSB_DWTXZCALPSB_MASK  0x7f
#define DWORD_0_DWTXZCALSB_DWTXZCALPSB_SHIFT 0
#define DWORD_0_DWMISCCTRL0_ADD    	(DWORD_0_BASE_ADD + 0x104)
#define DWORD_0_DWMISCCTRL0_MASK    0xffffffff
#define DWORD_0_DWMISCCTRL0_DWPHYCOMPLIANCE_MASK  	0x1
#define DWORD_0_DWMISCCTRL0_DWPHYCOMPLIANCE_SHIFT 	31
#define DWORD_0_DWMISCCTRL0_DWTXCKPARKLEVEL_MASK    0x1
#define DWORD_0_DWMISCCTRL0_DWTXCKPARKLEVEL_SHIFT   15
#define DWORD_0_DWMISCCTRL1_ADD    			(DWORD_0_BASE_ADD + 0x108)
#define DWORD_0_DWMODULEDEGRADESTATUS_ADD    (DWORD_0_BASE_ADD + 0x11c)
#define DWORD_0_DWPERBITCTRL0_ADD    	(DWORD_0_BASE_ADD + 0x140)
#define DWORD_0_DWPERBITCTRL1_ADD    	(DWORD_0_BASE_ADD + 0x144)
#define DWORD_0_DWPERBITCTRL2_ADD    	(DWORD_0_BASE_ADD + 0x148)
#define DWORD_0_DWPERBITCTRL3_ADD    	(DWORD_0_BASE_ADD + 0x14c)
#define DWORD_0_DWPERBITCTRL4_ADD    	(DWORD_0_BASE_ADD + 0x150)
#define DWORD_0_DWPERBITCTRL5_ADD    	(DWORD_0_BASE_ADD + 0x154)
#define DWORD_0_DWPERBITCTRL6_ADD    	(DWORD_0_BASE_ADD + 0x158)
#define DWORD_0_DWPERBITCTRL7_ADD    	(DWORD_0_BASE_ADD + 0x15c)
#define DWORD_0_DWPERBITCTRL8_ADD    	(DWORD_0_BASE_ADD + 0x160)
#define DWORD_0_DWPERBITCTRL9_ADD    	(DWORD_0_BASE_ADD + 0x164)
#define DWORD_0_DWPERBITCTRL10_ADD    	(DWORD_0_BASE_ADD + 0x168)
#define DWORD_0_DWPERBITCTRL11_ADD    	(DWORD_0_BASE_ADD + 0x16c)
#define DWORD_0_DWPERBITCTRL12_ADD    	(DWORD_0_BASE_ADD + 0x170)
#define DWORD_0_DWPERBITCTRL13_ADD    	(DWORD_0_BASE_ADD + 0x174)
#define DWORD_0_DWPERBITCTRL14_ADD    	(DWORD_0_BASE_ADD + 0x178)
#define DWORD_0_DWPERBITCTRL15_ADD    	(DWORD_0_BASE_ADD + 0x17c)
#define DWORD_0_DWPERBITCTRL16_ADD    	(DWORD_0_BASE_ADD + 0x180)
#define DWORD_0_DWPERBITCTRL17_ADD    	(DWORD_0_BASE_ADD + 0x184)
#define DWORD_0_DWPERBITCTRL18_ADD    	(DWORD_0_BASE_ADD + 0x188)
#define DWORD_0_DWPERBITCTRL19_ADD    	(DWORD_0_BASE_ADD + 0x18c)
#define DWORD_0_DWDCCCTRL1_ADD          (DWORD_0_BASE_ADD + 0x2c0)

#define MMPL_MMMODECTRL_ADD         (MMPL_BASE_ADD + 0x4)
#define MMPL_ZCALCTRL0_ADD          (MMPL_BASE_ADD + 0x1c)
#define MMPL_ZCALCTRL1_ADD          (MMPL_BASE_ADD + 0x20)
#define MMPL_ZCALCTRL4_ADD          (MMPL_BASE_ADD + 0x2c)
#define MMPL_PLLCTRL0_P0_ADD    	(MMPL_BASE_ADD + 0x44)
#define MMPL_PLLCTRL0_P1_ADD    	(MMPL_BASE_ADD + 0x48)
#define MMPL_PLLCTRL0_P2_ADD    	(MMPL_BASE_ADD + 0x4c)
#define MMPL_PLLCTRL0_P3_ADD    	(MMPL_BASE_ADD + 0x50)
#define MMPL_PLLCTRL1_P0_ADD    	(MMPL_BASE_ADD + 0x5c)
#define MMPL_PLLCTRL1_P1_ADD    	(MMPL_BASE_ADD + 0x60)
#define MMPL_PLLCTRL1_P2_ADD    	(MMPL_BASE_ADD + 0x64)
#define MMPL_PLLCTRL1_P3_ADD    	(MMPL_BASE_ADD + 0x68)
#define MMPL_PLLCTRL3_ADD    	(MMPL_BASE_ADD + 0x78)
#define MMPL_PLLCTRL4_ADD    	(MMPL_BASE_ADD + 0x7c)
#define MMPL_MMTRKCTRL_ADD      (MMPL_BASE_ADD + 0x128)
#define MMPL_MMMISCCTRL_MASK   	0xffffffff
#define MMPL_MMMISCCTRL_ADD    	(MMPL_BASE_ADD + 0x12c)
#define MMPL_MMMISCCTRL_MMPHYCOMPLIANCE_MASK  	0x1
#define MMPL_MMMISCCTRL_MMPHYCOMPLIANCE_SHIFT 	31

#define ACSM_ACSMTIMEOUTCTRL0_ADD    (ACSM_BASE_ADD + 0x5c)
#define ACSM_ACSMWAITDLY0_ADD    	 (ACSM_BASE_ADD + 0x20)  
#define ACSM_ACSMWAITDLY1_ADD    	 (ACSM_BASE_ADD + 0x24)
#define ACSM_ACSMLTSMSTATUS_ADD    	 (ACSM_BASE_ADD + 0x50)
#define ACSM_ACSMTIMEOUTCTRL1_ADD    (ACSM_BASE_ADD + 0x60)
#define ACSM_ACSMTRAINVAR0I0_MASK   	0xffffffff
#define ACSM_ACSMTRAINVAR0I0_ADD    	(ACSM_BASE_ADD + 0x98)
#define ACSM_ACSMTRAINVAR0I1_MASK   	0xffffffff
#define ACSM_ACSMTRAINVAR0I1_ADD    	(ACSM_BASE_ADD + 0x9c)
#define ACSM_ACSMTRAINVAR0I2_MASK   	0xffffffff
#define ACSM_ACSMTRAINVAR0I2_ADD    	(ACSM_BASE_ADD + 0xa0)
#define ACSM_ACSMTRAINVAR1I1_MASK   	0xffffffff
#define ACSM_ACSMTRAINVAR1I1_ADD    	(ACSM_BASE_ADD + 0xac)
#define ACSM_ACSMLTSMMSK0VAR4_ADD    (ACSM_BASE_ADD + 0x228)
#define ACSM_ACSMLTSMMSK0VAR5_ADD    (ACSM_BASE_ADD + 0x22c)
#define ACSM_ACSMLTSMMSK0VAR6_ADD    (ACSM_BASE_ADD + 0x230)
#define ACSM_ACSMLTSMMSK0VAR7_ADD    (ACSM_BASE_ADD + 0x234)

#define ACSMIM_ACSMINSTRREG25_ADD    (ACSMIM_BASE_ADD + 0x64)

#define DWORD_1_DWMODECTRL0_ADD    	(DWORD_1_BASE_ADD + 0x4)
#define DWORD_1_DWPUBMODECTRL_ADD    (DWORD_1_BASE_ADD + 0x6c)
#define DWORD_1_DWVREFVAR_ADD    	(DWORD_1_BASE_ADD + 0xdc)
#define DWORD_1_DWTXZCALSB_ADD    	(DWORD_1_BASE_ADD + 0xf8)
#define DWORD_1_DWTXZCALSB_DWTXZCALPSB_MASK  0x7f
#define DWORD_1_DWTXZCALSB_DWTXZCALPSB_SHIFT 0
#define DWORD_1_DWTXZCALSB_DWTXZCALNSB_MASK  0x7f
#define DWORD_1_DWTXZCALSB_DWTXZCALNSB_SHIFT 8
#define DWORD_1_DWMISCCTRL0_MASK   	0xffffffff
#define DWORD_1_DWMISCCTRL0_ADD    	(DWORD_1_BASE_ADD + 0x104)
#define DWORD_1_DWMISCCTRL0_DWPHYCOMPLIANCE_MASK  	0x1
#define DWORD_1_DWMISCCTRL0_DWPHYCOMPLIANCE_SHIFT 	31
#define DWORD_1_DWMISCCTRL0_DWTXCKPARKLEVEL_MASK  0x1
#define DWORD_1_DWMISCCTRL0_DWTXCKPARKLEVEL_SHIFT 15
#define DWORD_1_DWMISCCTRL1_ADD    	(DWORD_1_BASE_ADD + 0x108)
#define DWORD_1_DWMODULEDEGRADESTATUS_ADD    (DWORD_1_BASE_ADD + 0x11c)
#define DWORD_1_DWPERBITCTRL0_ADD    (DWORD_1_BASE_ADD + 0x140)
#define DWORD_1_DWPERBITCTRL1_ADD    (DWORD_1_BASE_ADD + 0x144)
#define DWORD_1_DWPERBITCTRL2_ADD    (DWORD_1_BASE_ADD + 0x148)
#define DWORD_1_DWPERBITCTRL3_ADD    (DWORD_1_BASE_ADD + 0x14c)
#define DWORD_1_DWPERBITCTRL4_ADD    (DWORD_1_BASE_ADD + 0x150)
#define DWORD_1_DWPERBITCTRL5_ADD    (DWORD_1_BASE_ADD + 0x154)
#define DWORD_1_DWPERBITCTRL6_ADD    (DWORD_1_BASE_ADD + 0x158)
#define DWORD_1_DWPERBITCTRL7_ADD    (DWORD_1_BASE_ADD + 0x15c)
#define DWORD_1_DWPERBITCTRL8_ADD    (DWORD_1_BASE_ADD + 0x160)
#define DWORD_1_DWPERBITCTRL9_ADD    (DWORD_1_BASE_ADD + 0x164)
#define DWORD_1_DWPERBITCTRL10_ADD    (DWORD_1_BASE_ADD + 0x168)
#define DWORD_1_DWPERBITCTRL11_ADD    (DWORD_1_BASE_ADD + 0x16c)
#define DWORD_1_DWPERBITCTRL12_ADD    (DWORD_1_BASE_ADD + 0x170)
#define DWORD_1_DWPERBITCTRL13_ADD    (DWORD_1_BASE_ADD + 0x174)
#define DWORD_1_DWPERBITCTRL14_ADD    (DWORD_1_BASE_ADD + 0x178)
#define DWORD_1_DWPERBITCTRL15_ADD    (DWORD_1_BASE_ADD + 0x17c)
#define DWORD_1_DWPERBITCTRL16_ADD    (DWORD_1_BASE_ADD + 0x180)
#define DWORD_1_DWPERBITCTRL17_ADD    (DWORD_1_BASE_ADD + 0x184)
#define DWORD_1_DWPERBITCTRL18_ADD    (DWORD_1_BASE_ADD + 0x188)
#define DWORD_1_DWPERBITCTRL19_ADD    (DWORD_1_BASE_ADD + 0x18c)
#define DWORD_1_DWDCCCTRL1_ADD        (DWORD_1_BASE_ADD + 0x2c0)

#endif /* __RCAR_UCIE_UCIE_PHY_H__ */
