/*
 *
 * Copyright (c) 2026 Renesas Electronics Corporation
 *
 * SPDX-License-Identifier: MIT
 *
 */

#ifndef __RCAR_UCIE_UCIE_CONTROLLER_H__
#define __RCAR_UCIE_UCIE_CONTROLLER_H__

#define IMP_SPECIFIC_SB_UNIT_BASE_ADD     RCAR_UCIE_BASE_ADD(0x41782000) // 0x282000
#define IMP_SPECIFIC_MB_UNIT_BASE_ADD     RCAR_UCIE_BASE_ADD(0x41783000) // 0x283000
#define DVSEC_UNIT_DSP_BASE_ADD           RCAR_UCIE_BASE_ADD(0x00000518) // 0x1000000

#define IMP_SPECIFIC_SB_UNIT_IMP_SB_CONFIG0_ADD    (IMP_SPECIFIC_SB_UNIT_BASE_ADD + 0x0)
#define IMP_SPECIFIC_SB_UNIT_IMP_SB_CONFIG2_ADD    (IMP_SPECIFIC_SB_UNIT_BASE_ADD + 0x8)
#define IMP_SPECIFIC_SB_UNIT_IMP_SB_CONFIG3_ADD    (IMP_SPECIFIC_SB_UNIT_BASE_ADD + 0xc)
#define IMP_SPECIFIC_SB_UNIT_IMP_SB_CONFIG4_ADD    (IMP_SPECIFIC_SB_UNIT_BASE_ADD + 0x10)
#define IMP_SPECIFIC_SB_UNIT_IMP_SB_CONFIG5_ADD    (IMP_SPECIFIC_SB_UNIT_BASE_ADD + 0x14)

#define IMP_SPECIFIC_MB_UNIT_IMP_MB_CONFIG4_ADD    (IMP_SPECIFIC_MB_UNIT_BASE_ADD + 0x10)
#define IMP_SPECIFIC_MB_UNIT_IMP_MB_CONFIG11_ADD    (IMP_SPECIFIC_MB_UNIT_BASE_ADD + 0x2c)

#define DVSEC_UNIT_DSP_DVSEC_UCIE_LINK_CONTROL_ADD    (DVSEC_UNIT_DSP_BASE_ADD + 0x10)

#endif /* __RCAR_UCIE_UCIE_CONTROLLER_H__ */
