/*
 * Copyright (c) 2026 Renesas Electronics Corporation
 *
 * SPDX-License-Identifier: MIT
 *
 */

/**
 * @defgroup PFC_PRIVATE PFC PRIVATE
 * @{
 * @brief PFC AIACC platform.
 *
 */

#ifndef R_PFC_PRVIATE_H
#define R_PFC_PRIVATE_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include "r_pfc_common_private.h"

/* PFC base adrress */
#define PFC_BASE_OFFSET    0x000U
#define PFC_GR_NUM  3

#define PFC_GR_0           (0x38080000U + PFC_BASE_OFFSET)
#define PFC_GR_1           (0x38080800U + PFC_BASE_OFFSET)
#define PFC_GR_2           (0x38081000U + PFC_BASE_OFFSET)

static const uint32_t pfc_gr_base[PFC_GR_NUM] =
{
    PFC_GR_0,
    PFC_GR_1,
    PFC_GR_2
};

#define HTX0                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_00, RCAR_PFC_PIN_00, RCAR_PFC_FUNC_0)
#define HRX0                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_00, RCAR_PFC_PIN_01, RCAR_PFC_FUNC_0)
#define HRTS0_N             GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_00, RCAR_PFC_PIN_02, RCAR_PFC_FUNC_0)
#define HCTS0_N             GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_00, RCAR_PFC_PIN_03, RCAR_PFC_FUNC_0)
#define HSCK0               GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_00, RCAR_PFC_PIN_04, RCAR_PFC_FUNC_0)
CREATE_GROUP(hscif0_grp, HTX0, HRX0, HRTS0_N, HCTS0_N, HSCK0)

#define TX0                 GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_00, RCAR_PFC_PIN_00, RCAR_PFC_FUNC_1)
#define RX0                 GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_00, RCAR_PFC_PIN_01, RCAR_PFC_FUNC_1)
#define RTS0_N              GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_00, RCAR_PFC_PIN_02, RCAR_PFC_FUNC_1)
#define CTS0_N              GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_00, RCAR_PFC_PIN_03, RCAR_PFC_FUNC_1)
#define SCK0                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_00, RCAR_PFC_PIN_04, RCAR_PFC_FUNC_1)
#define SCIF_CLK            GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_00, RCAR_PFC_PIN_05, RCAR_PFC_FUNC_0)
CREATE_GROUP(scif0_grp, TX0, RX0, RTS0_N, CTS0_N, SCK0, SCIF_CLK)

#define HTX1                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_00, RCAR_PFC_PIN_06, RCAR_PFC_FUNC_0)
#define HRX1                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_00, RCAR_PFC_PIN_07, RCAR_PFC_FUNC_0)
#define HRTS1_N             GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_00, RCAR_PFC_PIN_08, RCAR_PFC_FUNC_0)
#define HCTS1_N             GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_00, RCAR_PFC_PIN_09, RCAR_PFC_FUNC_0)
#define HSCK1               GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_00, RCAR_PFC_PIN_10, RCAR_PFC_FUNC_0)
CREATE_GROUP(hscif1_grp, HTX1, HRX1, HRTS1_N, HCTS1_N, HSCK1)

#define TX1                 GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_00, RCAR_PFC_PIN_06, RCAR_PFC_FUNC_1)
#define RX1                 GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_00, RCAR_PFC_PIN_07, RCAR_PFC_FUNC_1)
#define RTS1_N              GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_00, RCAR_PFC_PIN_08, RCAR_PFC_FUNC_1)
#define CTS1_N              GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_00, RCAR_PFC_PIN_09, RCAR_PFC_FUNC_1)
#define SCK1                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_00, RCAR_PFC_PIN_10, RCAR_PFC_FUNC_1)
CREATE_GROUP(scif1_grp, TX1, RX1, RTS1_N, CTS1_N, SCK1)

#define SDA0                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_01, RCAR_PFC_PIN_21, RCAR_PFC_FUNC_0)
#define SCL0                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_01, RCAR_PFC_PIN_20, RCAR_PFC_FUNC_0)
#define MODSEL_SDA0         GEN_ID(REG_MODSEL, RCAR_PFC_GROUP_01, RCAR_PFC_PIN_21, MODSEL_I2C_MODE)
#define MODSEL_SCL0         GEN_ID(REG_MODSEL, RCAR_PFC_GROUP_01, RCAR_PFC_PIN_20, MODSEL_I2C_MODE)
CREATE_GROUP(i2c0_grp, SDA0, SCL0, MODSEL_SDA0, MODSEL_SCL0)

#define SDA1                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_01, RCAR_PFC_PIN_23, RCAR_PFC_FUNC_0)
#define SCL1                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_01, RCAR_PFC_PIN_22, RCAR_PFC_FUNC_0)
#define MODSEL_SDA1         GEN_ID(REG_MODSEL, RCAR_PFC_GROUP_01, RCAR_PFC_PIN_23, MODSEL_I2C_MODE)
#define MODSEL_SCL1         GEN_ID(REG_MODSEL, RCAR_PFC_GROUP_01, RCAR_PFC_PIN_22, MODSEL_I2C_MODE)
CREATE_GROUP(i2c1_grp, SDA1, SCL1, MODSEL_SDA1, MODSEL_SCL1)

#define SDA2                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_01, RCAR_PFC_PIN_25, RCAR_PFC_FUNC_0)
#define SCL2                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_01, RCAR_PFC_PIN_24, RCAR_PFC_FUNC_0)
#define MODSEL_SDA2         GEN_ID(REG_MODSEL, RCAR_PFC_GROUP_01, RCAR_PFC_PIN_25, MODSEL_I2C_MODE)
#define MODSEL_SCL2         GEN_ID(REG_MODSEL, RCAR_PFC_GROUP_01, RCAR_PFC_PIN_24, MODSEL_I2C_MODE)
CREATE_GROUP(i2c2_grp, SDA2, SCL2, MODSEL_SDA2, MODSEL_SCL2)

#define SDA3                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_01, RCAR_PFC_PIN_27, RCAR_PFC_FUNC_0)
#define SCL3                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_01, RCAR_PFC_PIN_26, RCAR_PFC_FUNC_0)
#define MODSEL_SDA3         GEN_ID(REG_MODSEL, RCAR_PFC_GROUP_01, RCAR_PFC_PIN_27, MODSEL_I2C_MODE)
#define MODSEL_SCL3         GEN_ID(REG_MODSEL, RCAR_PFC_GROUP_01, RCAR_PFC_PIN_26, MODSEL_I2C_MODE)
CREATE_GROUP(i2c3_grp, SDA3, SCL3, MODSEL_SDA3, MODSEL_SCL3)

static const st_driver_group_t all_drv_groups[] = {
    {.module_id = MODULE_HSCIF0, .group = ADD_GROUP(hscif0_grp)},
    {.module_id = MODULE_SCIF0,  .group = ADD_GROUP(scif0_grp)},
    {.module_id = MODULE_HSCIF1, .group = ADD_GROUP(hscif1_grp)},
    {.module_id = MODULE_SCIF1,  .group = ADD_GROUP(scif1_grp)},
    {.module_id = MODULE_I2C0,  .group = ADD_GROUP(i2c0_grp)},
    {.module_id = MODULE_I2C1,  .group = ADD_GROUP(i2c1_grp)},
    {.module_id = MODULE_I2C2,  .group = ADD_GROUP(i2c2_grp)},
    {.module_id = MODULE_I2C3,  .group = ADD_GROUP(i2c3_grp)},
    // Add driver groups.
    {.module_id = MODULE_INVALID, .group = 0},
};

#ifdef __cplusplus
}
#endif

#endif /* R_PFC_PRIVATE_H */
