/*******************************************************************************
 * 
 * Copyright (c) 2026 Renesas Electronics Corporation
 * 
 * SPDX-License-Identifier: MIT
 * 
 *******************************************************************************/

/*******************************************************************************
 * DESCRIPTION   : Module Controller register header
 ******************************************************************************/

#ifndef MODULE_CONTROLLER_REGISTER_H_
#define MODULE_CONTROLLER_REGISTER_H_

/* MDUC-Region base address of Hier Structure. */
#if 0
#define BASE_ADDR_HIER_RT   (0x19440000U)   /* Hier Structure: 14, RT */
#endif

/* Module Controller register offset address */
#define MDLCNMSRESL_OFFSET      (0x0900U)
#define MDLCNMSRESSL_OFFSET     (0x0960U)
#define MDLCNPKCPROT1_OFFSET    (0x0CF4U)

/* Hier Structure: 14, RT */

/* Module System Reset Register [l] for [o], n = 14, l = 00 to 23 */
#define MDLC14MSRES00    (BASE_ADDR_HIER_RT + MDLCNMSRESL_OFFSET + 0x00U * 0x4U)
#define MDLC14MSRES01    (BASE_ADDR_HIER_RT + MDLCNMSRESL_OFFSET + 0x01U * 0x4U)
#define MDLC14MSRES02    (BASE_ADDR_HIER_RT + MDLCNMSRESL_OFFSET + 0x02U * 0x4U)
#define MDLC14MSRES03    (BASE_ADDR_HIER_RT + MDLCNMSRESL_OFFSET + 0x03U * 0x4U)
#define MDLC14MSRES04    (BASE_ADDR_HIER_RT + MDLCNMSRESL_OFFSET + 0x04U * 0x4U)
#define MDLC14MSRES05    (BASE_ADDR_HIER_RT + MDLCNMSRESL_OFFSET + 0x05U * 0x4U)
#define MDLC14MSRES06    (BASE_ADDR_HIER_RT + MDLCNMSRESL_OFFSET + 0x06U * 0x4U)
#define MDLC14MSRES07    (BASE_ADDR_HIER_RT + MDLCNMSRESL_OFFSET + 0x07U * 0x4U)
#define MDLC14MSRES08    (BASE_ADDR_HIER_RT + MDLCNMSRESL_OFFSET + 0x08U * 0x4U)
#define MDLC14MSRES09    (BASE_ADDR_HIER_RT + MDLCNMSRESL_OFFSET + 0x09U * 0x4U)
#define MDLC14MSRES10    (BASE_ADDR_HIER_RT + MDLCNMSRESL_OFFSET + 0x0AU * 0x4U)
#define MDLC14MSRES11    (BASE_ADDR_HIER_RT + MDLCNMSRESL_OFFSET + 0x0BU * 0x4U)
#define MDLC14MSRES12    (BASE_ADDR_HIER_RT + MDLCNMSRESL_OFFSET + 0x0CU * 0x4U)
#define MDLC14MSRES13    (BASE_ADDR_HIER_RT + MDLCNMSRESL_OFFSET + 0x0DU * 0x4U)
#define MDLC14MSRES14    (BASE_ADDR_HIER_RT + MDLCNMSRESL_OFFSET + 0x0EU * 0x4U)
#define MDLC14MSRES15    (BASE_ADDR_HIER_RT + MDLCNMSRESL_OFFSET + 0x0FU * 0x4U)
#define MDLC14MSRES16    (BASE_ADDR_HIER_RT + MDLCNMSRESL_OFFSET + 0x10U * 0x4U)
#define MDLC14MSRES17    (BASE_ADDR_HIER_RT + MDLCNMSRESL_OFFSET + 0x11U * 0x4U)
#define MDLC14MSRES18    (BASE_ADDR_HIER_RT + MDLCNMSRESL_OFFSET + 0x12U * 0x4U)
#define MDLC14MSRES19    (BASE_ADDR_HIER_RT + MDLCNMSRESL_OFFSET + 0x13U * 0x4U)
#define MDLC14MSRES20    (BASE_ADDR_HIER_RT + MDLCNMSRESL_OFFSET + 0x14U * 0x4U)
#define MDLC14MSRES21    (BASE_ADDR_HIER_RT + MDLCNMSRESL_OFFSET + 0x15U * 0x4U)

/* Module System Reset Status Register [l] for [o], n = 14, l = 00 to 23 */
#define MDLC14MSRESS00    (BASE_ADDR_HIER_RT + MDLCNMSRESSL_OFFSET + 0x00U * 0x4U)
#define MDLC14MSRESS01    (BASE_ADDR_HIER_RT + MDLCNMSRESSL_OFFSET + 0x01U * 0x4U)
#define MDLC14MSRESS02    (BASE_ADDR_HIER_RT + MDLCNMSRESSL_OFFSET + 0x02U * 0x4U)
#define MDLC14MSRESS03    (BASE_ADDR_HIER_RT + MDLCNMSRESSL_OFFSET + 0x03U * 0x4U)
#define MDLC14MSRESS04    (BASE_ADDR_HIER_RT + MDLCNMSRESSL_OFFSET + 0x04U * 0x4U)
#define MDLC14MSRESS05    (BASE_ADDR_HIER_RT + MDLCNMSRESSL_OFFSET + 0x05U * 0x4U)
#define MDLC14MSRESS06    (BASE_ADDR_HIER_RT + MDLCNMSRESSL_OFFSET + 0x06U * 0x4U)
#define MDLC14MSRESS07    (BASE_ADDR_HIER_RT + MDLCNMSRESSL_OFFSET + 0x07U * 0x4U)
#define MDLC14MSRESS08    (BASE_ADDR_HIER_RT + MDLCNMSRESSL_OFFSET + 0x08U * 0x4U)
#define MDLC14MSRESS09    (BASE_ADDR_HIER_RT + MDLCNMSRESSL_OFFSET + 0x09U * 0x4U)
#define MDLC14MSRESS10    (BASE_ADDR_HIER_RT + MDLCNMSRESSL_OFFSET + 0x0AU * 0x4U)
#define MDLC14MSRESS11    (BASE_ADDR_HIER_RT + MDLCNMSRESSL_OFFSET + 0x0BU * 0x4U)
#define MDLC14MSRESS12    (BASE_ADDR_HIER_RT + MDLCNMSRESSL_OFFSET + 0x0CU * 0x4U)
#define MDLC14MSRESS13    (BASE_ADDR_HIER_RT + MDLCNMSRESSL_OFFSET + 0x0DU * 0x4U)
#define MDLC14MSRESS14    (BASE_ADDR_HIER_RT + MDLCNMSRESSL_OFFSET + 0x0EU * 0x4U)
#define MDLC14MSRESS15    (BASE_ADDR_HIER_RT + MDLCNMSRESSL_OFFSET + 0x0FU * 0x4U)
#define MDLC14MSRESS16    (BASE_ADDR_HIER_RT + MDLCNMSRESSL_OFFSET + 0x10U * 0x4U)
#define MDLC14MSRESS17    (BASE_ADDR_HIER_RT + MDLCNMSRESSL_OFFSET + 0x11U * 0x4U)
#define MDLC14MSRESS18    (BASE_ADDR_HIER_RT + MDLCNMSRESSL_OFFSET + 0x12U * 0x4U)
#define MDLC14MSRESS19    (BASE_ADDR_HIER_RT + MDLCNMSRESSL_OFFSET + 0x13U * 0x4U)
#define MDLC14MSRESS20    (BASE_ADDR_HIER_RT + MDLCNMSRESSL_OFFSET + 0x14U * 0x4U)
#define MDLC14MSRESS21    (BASE_ADDR_HIER_RT + MDLCNMSRESSL_OFFSET + 0x15U * 0x4U)

/* Module Controller Register 1 Key Code Protection Register for [o], n = 14 */
#define MDLC14PKCPROT1  (BASE_ADDR_HIER_RT + MDLCNPKCPROT1_OFFSET)

#endif /* MODULE_CONTROLLER_REGISTER_H_ */
