/*
 *
 * Copyright (c) 2025 Renesas Electronics Corporation
 *
 * SPDX-License-Identifier: MIT
 *
 */

#ifndef R_POWER_DOMAIN_ID_H
#define R_POWER_DOMAIN_ID_H

/**
 * @defgroup AIACC_Power_Domain_ID AIACC Power Domain ID
 * @{
 * @brief This module provides typedef of Power Domain ID.
 *
 * The full list of Power Domain IDs is defined in SCP Firmware. Only reference this enum for compatibility with the driver interface.
 */

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief AIACC Power domain IDs.
 */
typedef enum {
    AIACC_POWER_DOMAIN_ID_VIO0,
    AIACC_POWER_DOMAIN_ID_VIO1,
    AIACC_POWER_DOMAIN_ID_IM0,
    AIACC_POWER_DOMAIN_ID_IM1,
    AIACC_POWER_DOMAIN_ID_IM2,
    AIACC_POWER_DOMAIN_ID_IM3,
    AIACC_POWER_DOMAIN_ID_NPU0C00,
    AIACC_POWER_DOMAIN_ID_NPU0C01,
    AIACC_POWER_DOMAIN_ID_NPU0C02,
    AIACC_POWER_DOMAIN_ID_NPU0C10,
    AIACC_POWER_DOMAIN_ID_NPU0C11,
    AIACC_POWER_DOMAIN_ID_NPU0C12,
    AIACC_POWER_DOMAIN_ID_NPU0C20,
    AIACC_POWER_DOMAIN_ID_NPU0C21,
    AIACC_POWER_DOMAIN_ID_NPU0C22,
    AIACC_POWER_DOMAIN_ID_NPU0C30,
    AIACC_POWER_DOMAIN_ID_NPU0C31,
    AIACC_POWER_DOMAIN_ID_NPU0C32,
    AIACC_POWER_DOMAIN_ID_NPU0,
    AIACC_POWER_DOMAIN_ID_DSP0,
    AIACC_POWER_DOMAIN_ID_NPU1C00,
    AIACC_POWER_DOMAIN_ID_NPU1C01,
    AIACC_POWER_DOMAIN_ID_NPU1C02,
    AIACC_POWER_DOMAIN_ID_NPU1C10,
    AIACC_POWER_DOMAIN_ID_NPU1C11,
    AIACC_POWER_DOMAIN_ID_NPU1C12,
    AIACC_POWER_DOMAIN_ID_NPU1C20,
    AIACC_POWER_DOMAIN_ID_NPU1C21,
    AIACC_POWER_DOMAIN_ID_NPU1C22,
    AIACC_POWER_DOMAIN_ID_NPU1C30,
    AIACC_POWER_DOMAIN_ID_NPU1C31,
    AIACC_POWER_DOMAIN_ID_NPU1C32,
    AIACC_POWER_DOMAIN_ID_NPU1,
    AIACC_POWER_DOMAIN_ID_DSP1,
    AIACC_POWER_DOMAIN_ID_NPU2C00,
    AIACC_POWER_DOMAIN_ID_NPU2C01,
    AIACC_POWER_DOMAIN_ID_NPU2C02,
    AIACC_POWER_DOMAIN_ID_NPU2C10,
    AIACC_POWER_DOMAIN_ID_NPU2C11,
    AIACC_POWER_DOMAIN_ID_NPU2C12,
    AIACC_POWER_DOMAIN_ID_NPU2C20,
    AIACC_POWER_DOMAIN_ID_NPU2C21,
    AIACC_POWER_DOMAIN_ID_NPU2C22,
    AIACC_POWER_DOMAIN_ID_NPU2C30,
    AIACC_POWER_DOMAIN_ID_NPU2C31,
    AIACC_POWER_DOMAIN_ID_NPU2C32,
    AIACC_POWER_DOMAIN_ID_NPU2,
    AIACC_POWER_DOMAIN_ID_DSP2,
    AIACC_POWER_DOMAIN_ID_NPU3C00,
    AIACC_POWER_DOMAIN_ID_NPU3C01,
    AIACC_POWER_DOMAIN_ID_NPU3C02,
    AIACC_POWER_DOMAIN_ID_NPU3C10,
    AIACC_POWER_DOMAIN_ID_NPU3C11,
    AIACC_POWER_DOMAIN_ID_NPU3C12,
    AIACC_POWER_DOMAIN_ID_NPU3C20,
    AIACC_POWER_DOMAIN_ID_NPU3C21,
    AIACC_POWER_DOMAIN_ID_NPU3C22,
    AIACC_POWER_DOMAIN_ID_NPU3C30,
    AIACC_POWER_DOMAIN_ID_NPU3C31,
    AIACC_POWER_DOMAIN_ID_NPU3C32,
    AIACC_POWER_DOMAIN_ID_NPU3,
    AIACC_POWER_DOMAIN_ID_DSP3,
    AIACC_POWER_DOMAIN_ID_COUNT
} e_aiacc_power_domain_id_t;

#ifdef __cplusplus
}
#endif

/** @} */ // end of AIACC_Power_Domain_ID

#endif /* R_POWER_DOMAIN_ID_H */

