/*
 *
 * Copyright (c) 2025 Renesas Electronics Corporation
 *
 * SPDX-License-Identifier: MIT
 *
 */

#ifndef RCAR_UCIE_UCIE_CONTROLLER_H
#define RCAR_UCIE_UCIE_CONTROLLER_H

/*-----  Registers Address-Block Base Address  -----*/
#define IMP_SPECIFIC_SB_UNIT_BASE_ADD     RCAR_UCIE_BASE_ADD(0x41782000) //0x282000
#define IMP_SPECIFIC_MB_UNIT_BASE_ADD     RCAR_UCIE_BASE_ADD(0x41783000) //0x283000
#define DVSEC_UNIT_DSP_BASE_ADD           RCAR_UCIE_BASE_ADD(0x000004b4) //0x1000000
#define CXL_DVSEC_UNIT_DSP_BASE_ADD       RCAR_UCIE_BASE_ADD(0x000003b0) //0x1f00000

/*-----  IMP_SPECIFIC_SB_UNIT detail register offset  -----*/
#define IMP_SPECIFIC_SB_UNIT_IMP_SB_CONFIG0_ADD    (IMP_SPECIFIC_SB_UNIT_BASE_ADD + 0x0)
#define IMP_SPECIFIC_SB_UNIT_IMP_SB_CONFIG2_ADD    (IMP_SPECIFIC_SB_UNIT_BASE_ADD + 0x8)
#define IMP_SPECIFIC_SB_UNIT_IMP_SB_CONFIG3_ADD    (IMP_SPECIFIC_SB_UNIT_BASE_ADD + 0xc)
#define IMP_SPECIFIC_SB_UNIT_IMP_SB_CONFIG4_ADD    (IMP_SPECIFIC_SB_UNIT_BASE_ADD + 0x10)
#define IMP_SPECIFIC_SB_UNIT_IMP_SB_CONFIG5_ADD    (IMP_SPECIFIC_SB_UNIT_BASE_ADD + 0x14)

/*-----  IMP_SPECIFIC_MB_UNIT detail register offset  -----*/
#define IMP_SPECIFIC_MB_UNIT_IMP_MB_CONFIG4_ADD    (IMP_SPECIFIC_MB_UNIT_BASE_ADD + 0x10)
#define IMP_SPECIFIC_MB_UNIT_IMP_MB_CONFIG11_ADD   (IMP_SPECIFIC_MB_UNIT_BASE_ADD + 0x2c)

/*-----  DVSEC_UNIT_DSP detail register offset  -----*/
#define DVSEC_UNIT_DSP_DVSEC_UCIE_LINK_CONTROL_ADD    (DVSEC_UNIT_DSP_BASE_ADD + 0x10)

/*-----  CXL_DVSEC_UNIT_DSP detail register offset  -----*/
#define CXL_DVSEC_UNIT_DSP_CXL_DVSEC_FLEX_CTL_STATUS_ADD    (CXL_DVSEC_UNIT_DSP_BASE_ADD + 0xc)

#endif /* RCAR_UCIE_UCIE_CONTROLLER_H */
