/*
 *
 * Copyright (c) 2025 Renesas Electronics Corporation
 *
 * SPDX-License-Identifier: MIT
 *
 */

#ifndef RCAR_UCIE_UCIE_PHY_H
#define RCAR_UCIE_UCIE_PHY_H

#define DWORD_0_BASE_ADD              RCAR_UCIE_BASE_ADD(0x41f00000U) // 0x300000
#define MMPL_BASE_ADD                 RCAR_UCIE_BASE_ADD(0x41f01000U) // 0x301000
#define ACSM_BASE_ADD                 RCAR_UCIE_BASE_ADD(0x41f02000U) // 0x302000
#define ACSMIM_BASE_ADD               RCAR_UCIE_BASE_ADD(0x41f03000U) // 0x303000
#define DWORD_1_BASE_ADD              RCAR_UCIE_BASE_ADD(0x41f10000U) // 0x310000

#define MMPL_MMMODECTRL_ADD    (MMPL_BASE_ADD + 0x4U)
#define MMPL_MODULEDEGRADESTATUS_ADD    (MMPL_BASE_ADD + 0x8U)
#define MMPL_ZCALCTRL0_ADD    (MMPL_BASE_ADD + 0x1cU)
#define MMPL_ZCALCTRL1_ADD    (MMPL_BASE_ADD + 0x20U)
#define MMPL_ZCALCTRL4_ADD    (MMPL_BASE_ADD + 0x2cU)
#define MMPL_PLLCTRL0_ADD    (MMPL_BASE_ADD + 0x44U)
#define MMPL_PLLCTRL1_ADD    (MMPL_BASE_ADD + 0x48U)
#define MMPL_PLLCTRL3_ADD    (MMPL_BASE_ADD + 0x50U)
#define MMPL_PLLCTRL4_ADD    (MMPL_BASE_ADD + 0x54U)
#define MMPL_CSRADDR2_ADD    (MMPL_BASE_ADD + 0x78U)
#define MMPL_CSRADDR5_ADD    (MMPL_BASE_ADD + 0x84U)
#define MMPL_CSRADDR10_ADD    (MMPL_BASE_ADD + 0x98U)
#define MMPL_CSRADDR11_ADD    (MMPL_BASE_ADD + 0x9cU)
#define MMPL_MMTRKCTRL_ADD    (MMPL_BASE_ADD + 0x100U)


#define DWORD_0_DWMODECTRL0_ADD    (DWORD_0_BASE_ADD + 0x4U)
#define DWORD_0_DWMODECTRL0_MASK   0xffffffff
#define DWORD_0_DWMODECTRL0_DWRXCTLCLKSEL_MASK  0x1U
#define DWORD_0_DWMODECTRL0_DWRXCTLCLKSEL_SHIFT 23
#define DWORD_0_DWMODECTRL0_DWRXLATALIGN_MASK  0x3U
#define DWORD_0_DWMODECTRL0_DWRXLATALIGN_SHIFT 0
#define DWORD_0_DWRXLATCTRL_ADD    (DWORD_0_BASE_ADD + 0x50U)
#define DWORD_0_DWRXLATCTRL_MASK   0xffffffff
#define DWORD_0_DWRXLATCTRL_DWRXVLDMARGIN_MASK  0x1U
#define DWORD_0_DWRXLATCTRL_DWRXVLDMARGIN_SHIFT 6
#define DWORD_0_DWPUBMODECTRL_ADD    (DWORD_0_BASE_ADD + 0x6cU)
#define DWORD_0_DWVREFVAR_ADD    (DWORD_0_BASE_ADD + 0xdcU)
#define DWORD_0_DWTXZCALSB_ADD    (DWORD_0_BASE_ADD + 0xf8U)
#define DWORD_0_DWMISCCTRL0_ADD    (DWORD_0_BASE_ADD + 0x104U)
#define DWORD_0_DWMISCCTRL1_ADD    (DWORD_0_BASE_ADD + 0x108U)
#define DWORD_0_DWMODULEDEGRADESTATUS_ADD    (DWORD_0_BASE_ADD + 0x11cU)
#define DWORD_0_DWPERBITCTRL0_ADD    (DWORD_0_BASE_ADD + 0x140U)
#define DWORD_0_DWPERBITCTRL1_ADD    (DWORD_0_BASE_ADD + 0x144U)
#define DWORD_0_DWPERBITCTRL2_ADD    (DWORD_0_BASE_ADD + 0x148U)
#define DWORD_0_DWPERBITCTRL3_ADD    (DWORD_0_BASE_ADD + 0x14cU)
#define DWORD_0_DWPERBITCTRL4_ADD    (DWORD_0_BASE_ADD + 0x150U)
#define DWORD_0_DWPERBITCTRL5_ADD    (DWORD_0_BASE_ADD + 0x154U)
#define DWORD_0_DWPERBITCTRL6_ADD    (DWORD_0_BASE_ADD + 0x158U)
#define DWORD_0_DWPERBITCTRL7_ADD    (DWORD_0_BASE_ADD + 0x15cU)
#define DWORD_0_DWPERBITCTRL8_ADD    (DWORD_0_BASE_ADD + 0x160U)
#define DWORD_0_DWPERBITCTRL9_ADD    (DWORD_0_BASE_ADD + 0x164U)
#define DWORD_0_DWPERBITCTRL10_ADD    (DWORD_0_BASE_ADD + 0x168U)
#define DWORD_0_DWPERBITCTRL11_ADD    (DWORD_0_BASE_ADD + 0x16cU)
#define DWORD_0_DWPERBITCTRL12_ADD    (DWORD_0_BASE_ADD + 0x170U)
#define DWORD_0_DWPERBITCTRL13_ADD    (DWORD_0_BASE_ADD + 0x174U)
#define DWORD_0_DWPERBITCTRL14_ADD    (DWORD_0_BASE_ADD + 0x178U)
#define DWORD_0_DWPERBITCTRL15_ADD    (DWORD_0_BASE_ADD + 0x17cU)
#define DWORD_0_DWPERBITCTRL16_ADD    (DWORD_0_BASE_ADD + 0x180U)
#define DWORD_0_DWPERBITCTRL17_ADD    (DWORD_0_BASE_ADD + 0x184U)
#define DWORD_0_DWPERBITCTRL18_ADD    (DWORD_0_BASE_ADD + 0x188U)
#define DWORD_0_DWPERBITCTRL19_ADD    (DWORD_0_BASE_ADD + 0x18cU)
#define DWORD_0_DWDCCCTRL1_ADD        (DWORD_0_BASE_ADD + 0x2c0U)

#define DWORD_1_DWMODECTRL0_ADD    (DWORD_1_BASE_ADD + 0x4)
#define DWORD_1_DWMODECTRL0_MASK   0xffffffff
#define DWORD_1_DWMODECTRL0_DWRXCTLCLKSEL_MASK  0x1U
#define DWORD_1_DWMODECTRL0_DWRXCTLCLKSEL_SHIFT 23
#define DWORD_1_DWMODECTRL0_DWRXLATALIGN_MASK  0x3U
#define DWORD_1_DWMODECTRL0_DWRXLATALIGN_SHIFT 0
#define DWORD_1_DWRXLATCTRL_ADD    (DWORD_1_BASE_ADD + 0x50)
#define DWORD_1_DWRXLATCTRL_MASK   0xffffffff
#define DWORD_1_DWRXLATCTRL_DWRXVLDMARGIN_MASK  0x1U
#define DWORD_1_DWRXLATCTRL_DWRXVLDMARGIN_SHIFT 6
#define DWORD_1_DWPUBMODECTRL_ADD    (DWORD_1_BASE_ADD + 0x6c)
#define DWORD_1_DWVREFVAR_ADD    (DWORD_1_BASE_ADD + 0xdc)
#define DWORD_1_DWTXZCALSB_ADD    (DWORD_1_BASE_ADD + 0xf8)
#define DWORD_1_DWMISCCTRL0_ADD    (DWORD_1_BASE_ADD + 0x104U)
#define DWORD_1_DWMISCCTRL0_MASK   0xffffffff
#define DWORD_1_DWMISCCTRL0_DWTXCKPARKLEVEL_MASK  0x1U
#define DWORD_1_DWMISCCTRL0_DWTXCKPARKLEVEL_SHIFT 15
#define DWORD_1_DWMISCCTRL1_ADD    (DWORD_1_BASE_ADD + 0x108)
#define DWORD_1_DWMODULEDEGRADESTATUS_ADD    (DWORD_1_BASE_ADD + 0x11c)
#define DWORD_1_DWPERBITCTRL0_ADD    (DWORD_1_BASE_ADD + 0x140)
#define DWORD_1_DWPERBITCTRL1_ADD    (DWORD_1_BASE_ADD + 0x144)
#define DWORD_1_DWPERBITCTRL2_ADD    (DWORD_1_BASE_ADD + 0x148)
#define DWORD_1_DWPERBITCTRL3_ADD    (DWORD_1_BASE_ADD + 0x14c)
#define DWORD_1_DWPERBITCTRL4_ADD    (DWORD_1_BASE_ADD + 0x150)
#define DWORD_1_DWPERBITCTRL5_ADD    (DWORD_1_BASE_ADD + 0x154)
#define DWORD_1_DWPERBITCTRL6_ADD    (DWORD_1_BASE_ADD + 0x158)
#define DWORD_1_DWPERBITCTRL7_ADD    (DWORD_1_BASE_ADD + 0x15c)
#define DWORD_1_DWPERBITCTRL8_ADD    (DWORD_1_BASE_ADD + 0x160)
#define DWORD_1_DWPERBITCTRL9_ADD    (DWORD_1_BASE_ADD + 0x164)
#define DWORD_1_DWPERBITCTRL10_ADD    (DWORD_1_BASE_ADD + 0x168)
#define DWORD_1_DWPERBITCTRL11_ADD    (DWORD_1_BASE_ADD + 0x16c)
#define DWORD_1_DWPERBITCTRL12_ADD    (DWORD_1_BASE_ADD + 0x170)
#define DWORD_1_DWPERBITCTRL13_ADD    (DWORD_1_BASE_ADD + 0x174)
#define DWORD_1_DWPERBITCTRL14_ADD    (DWORD_1_BASE_ADD + 0x178)
#define DWORD_1_DWPERBITCTRL15_ADD    (DWORD_1_BASE_ADD + 0x17c)
#define DWORD_1_DWPERBITCTRL16_ADD    (DWORD_1_BASE_ADD + 0x180)
#define DWORD_1_DWPERBITCTRL17_ADD    (DWORD_1_BASE_ADD + 0x184)
#define DWORD_1_DWPERBITCTRL18_ADD    (DWORD_1_BASE_ADD + 0x188)
#define DWORD_1_DWPERBITCTRL19_ADD    (DWORD_1_BASE_ADD + 0x18c)
#define DWORD_1_DWDCCCTRL1_ADD    (DWORD_1_BASE_ADD + 0x2c0U)

#define ACSMIM_ACSMINSTRREG5_ADD    (ACSMIM_BASE_ADD + 0x14)
#define ACSMIM_ACSMINSTRREG6_ADD    (ACSMIM_BASE_ADD + 0x18)
#define ACSMIM_ACSMINSTRREG7_ADD    (ACSMIM_BASE_ADD + 0x1c)
#define ACSMIM_ACSMINSTRREG8_ADD    (ACSMIM_BASE_ADD + 0x20)
#define ACSMIM_ACSMINSTRREG9_ADD    (ACSMIM_BASE_ADD + 0x24)
#define ACSMIM_ACSMINSTRREG10_ADD    (ACSMIM_BASE_ADD + 0x28)
#define ACSMIM_ACSMINSTRREG11_ADD    (ACSMIM_BASE_ADD + 0x2c)
#define ACSMIM_ACSMINSTRREG12_ADD    (ACSMIM_BASE_ADD + 0x30)
#define ACSMIM_ACSMINSTRREG13_ADD    (ACSMIM_BASE_ADD + 0x34)
#define ACSMIM_ACSMINSTRREG14_ADD    (ACSMIM_BASE_ADD + 0x38)
#define ACSMIM_ACSMINSTRREG15_ADD    (ACSMIM_BASE_ADD + 0x3c)
#define ACSMIM_ACSMINSTRREG16_ADD    (ACSMIM_BASE_ADD + 0x40)
#define ACSMIM_ACSMINSTRREG17_ADD    (ACSMIM_BASE_ADD + 0x44)
#define ACSMIM_ACSMINSTRREG18_ADD    (ACSMIM_BASE_ADD + 0x48)
#define ACSMIM_ACSMINSTRREG19_ADD    (ACSMIM_BASE_ADD + 0x4c)
#define ACSMIM_ACSMINSTRREG20_ADD    (ACSMIM_BASE_ADD + 0x50)
#define ACSMIM_ACSMINSTRREG21_ADD    (ACSMIM_BASE_ADD + 0x54)
#define ACSMIM_ACSMINSTRREG22_ADD    (ACSMIM_BASE_ADD + 0x58)
#define ACSMIM_ACSMINSTRREG23_ADD    (ACSMIM_BASE_ADD + 0x5c)
#define ACSMIM_ACSMINSTRREG24_ADD    (ACSMIM_BASE_ADD + 0x60)
#define ACSMIM_ACSMINSTRREG25_ADD    (ACSMIM_BASE_ADD + 0x64)
#define ACSMIM_ACSMINSTRREG26_ADD    (ACSMIM_BASE_ADD + 0x68)
#define ACSMIM_ACSMINSTRREG27_ADD    (ACSMIM_BASE_ADD + 0x6c)
#define ACSMIM_ACSMINSTRREG28_ADD    (ACSMIM_BASE_ADD + 0x70)
#define ACSMIM_ACSMINSTRREG29_ADD    (ACSMIM_BASE_ADD + 0x74)
#define ACSMIM_ACSMINSTRREG30_ADD    (ACSMIM_BASE_ADD + 0x78)
#define ACSMIM_ACSMINSTRREG31_ADD    (ACSMIM_BASE_ADD + 0x7c)
#define ACSMIM_ACSMINSTRREG32_ADD    (ACSMIM_BASE_ADD + 0x80)
#define ACSMIM_ACSMINSTRREG33_ADD    (ACSMIM_BASE_ADD + 0x84)
#define ACSMIM_ACSMINSTRREG34_ADD    (ACSMIM_BASE_ADD + 0x88)
#define ACSMIM_ACSMINSTRREG35_ADD    (ACSMIM_BASE_ADD + 0x8c)
#define ACSMIM_ACSMINSTRREG36_ADD    (ACSMIM_BASE_ADD + 0x90)
#define ACSMIM_ACSMINSTRREG37_ADD    (ACSMIM_BASE_ADD + 0x94)
#define ACSMIM_ACSMINSTRREG38_ADD    (ACSMIM_BASE_ADD + 0x98)
#define ACSMIM_ACSMINSTRREG39_ADD    (ACSMIM_BASE_ADD + 0x9c)
#define ACSMIM_ACSMINSTRREG40_ADD    (ACSMIM_BASE_ADD + 0xa0)
#define ACSMIM_ACSMINSTRREG68_ADD    (ACSMIM_BASE_ADD + 0x110)
#define ACSMIM_ACSMINSTRREG69_ADD    (ACSMIM_BASE_ADD + 0x114)
#define ACSMIM_ACSMINSTRREG70_ADD    (ACSMIM_BASE_ADD + 0x118)
#define ACSMIM_ACSMINSTRREG71_ADD    (ACSMIM_BASE_ADD + 0x11c)
#define ACSMIM_ACSMINSTRREG72_ADD    (ACSMIM_BASE_ADD + 0x120)
#define ACSMIM_ACSMINSTRREG73_ADD    (ACSMIM_BASE_ADD + 0x124)
#define ACSMIM_ACSMINSTRREG74_ADD    (ACSMIM_BASE_ADD + 0x128)
#define ACSMIM_ACSMINSTRREG75_ADD    (ACSMIM_BASE_ADD + 0x12c)
#define ACSMIM_ACSMINSTRREG76_ADD    (ACSMIM_BASE_ADD + 0x130)
#define ACSMIM_ACSMINSTRREG77_ADD    (ACSMIM_BASE_ADD + 0x134)
#define ACSMIM_ACSMINSTRREG78_ADD    (ACSMIM_BASE_ADD + 0x138)
#define ACSMIM_ACSMINSTRREG79_ADD    (ACSMIM_BASE_ADD + 0x13c)
#define ACSMIM_ACSMINSTRREG80_ADD    (ACSMIM_BASE_ADD + 0x140)
#define ACSMIM_ACSMINSTRREG81_ADD    (ACSMIM_BASE_ADD + 0x144)
#define ACSMIM_ACSMINSTRREG82_ADD    (ACSMIM_BASE_ADD + 0x148)
#define ACSMIM_ACSMINSTRREG83_ADD    (ACSMIM_BASE_ADD + 0x14c)
#define ACSMIM_ACSMINSTRREG84_ADD    (ACSMIM_BASE_ADD + 0x150)
#define ACSMIM_ACSMINSTRREG85_ADD    (ACSMIM_BASE_ADD + 0x154)
#define ACSMIM_ACSMINSTRREG86_ADD    (ACSMIM_BASE_ADD + 0x158)
#define ACSMIM_ACSMINSTRREG87_ADD    (ACSMIM_BASE_ADD + 0x15c)
#define ACSMIM_ACSMINSTRREG88_ADD    (ACSMIM_BASE_ADD + 0x160)
#define ACSMIM_ACSMINSTRREG89_ADD    (ACSMIM_BASE_ADD + 0x164)
#define ACSMIM_ACSMINSTRREG90_ADD    (ACSMIM_BASE_ADD + 0x168)
#define ACSMIM_ACSMINSTRREG91_ADD    (ACSMIM_BASE_ADD + 0x16c)
#define ACSMIM_ACSMINSTRREG92_ADD    (ACSMIM_BASE_ADD + 0x170)
#define ACSMIM_ACSMINSTRREG93_ADD    (ACSMIM_BASE_ADD + 0x174)
#define ACSMIM_ACSMINSTRREG94_ADD    (ACSMIM_BASE_ADD + 0x178)
#define ACSMIM_ACSMINSTRREG95_ADD    (ACSMIM_BASE_ADD + 0x17c)
#define ACSMIM_ACSMINSTRREG96_ADD    (ACSMIM_BASE_ADD + 0x180)
#define ACSMIM_ACSMINSTRREG97_ADD    (ACSMIM_BASE_ADD + 0x184)
#define ACSMIM_ACSMINSTRREG98_ADD    (ACSMIM_BASE_ADD + 0x188)
#define ACSMIM_ACSMINSTRREG99_ADD    (ACSMIM_BASE_ADD + 0x18c)
#define ACSMIM_ACSMINSTRREG100_ADD    (ACSMIM_BASE_ADD + 0x190)

#define ACSM_ACSMCTRL_ADD    (ACSM_BASE_ADD + 0x0)
#define ACSM_ACSMCTRL_MASK   0xffffffff
#define ACSM_ACSMCTRL_ACSMSTOPADDR_MASK  0x7fU
#define ACSM_ACSMCTRL_ACSMSTOPADDR_SHIFT 24
#define ACSM_ACSMSEQ0CTRL_ADD    (ACSM_BASE_ADD + 0x4)
#define ACSM_ACSMSEQ0CTRL_MASK   0xffffffff
#define ACSM_ACSMSEQ0CTRL_ACSMSEQ0STOPADDR_MASK  0x7fU
#define ACSM_ACSMSEQ0CTRL_ACSMSEQ0STOPADDR_SHIFT 8
#define ACSM_ACSMSEQ1CTRL_ADD    (ACSM_BASE_ADD + 0x8)
#define ACSM_ACSMSEQ1CTRL_MASK   0xffffffff
#define ACSM_ACSMSEQ1CTRL_ACSMSEQ1STOPADDR_MASK  0x7fU
#define ACSM_ACSMSEQ1CTRL_ACSMSEQ1STOPADDR_SHIFT 8
#define ACSM_ACSMWAITDLY0_ADD    (ACSM_BASE_ADD + 0x20U)
#define ACSM_ACSMWAITDLY1_ADD    (ACSM_BASE_ADD + 0x24U)
#define ACSM_ACSMLTSMSTATUS_ADD    (ACSM_BASE_ADD + 0x50U)
#define ACSM_ACSMTIMEOUTCTRL0_ADD    (ACSM_BASE_ADD + 0x5cU)
#define ACSM_ACSMTIMEOUTCTRL1_ADD    (ACSM_BASE_ADD + 0x60U)
#define ACSM_ACSMLOOPVAR1_ADD    (ACSM_BASE_ADD + 0x7c)
#define ACSM_ACSMTRAINVAR0I0_ADD    (ACSM_BASE_ADD + 0x98)
#define ACSM_ACSMTRAINVAR0I0_MASK   0xffffffff
#define ACSM_ACSMTRAINVAR0I1_ADD    (ACSM_BASE_ADD + 0x9c)
#define ACSM_ACSMTRAINVAR0I1_MASK   0xffffffff
#define ACSM_ACSMTRAINVAR0I2_ADD    (ACSM_BASE_ADD + 0xa0)
#define ACSM_ACSMTRAINVAR0I2_MASK   0xffffffff
#define ACSM_ACSMTRAINVAR1I1_ADD    (ACSM_BASE_ADD + 0xac)
#define ACSM_ACSMTRAINVAR1I1_MASK   0xffffffff
#define ACSM_ACSMLTSMINDEX0VAR14_ADD    (ACSM_BASE_ADD + 0x150)
#define ACSM_ACSMLTSMINDEX0VAR14_MASK   0xffffffff
#define ACSM_ACSMLTSMINDEX0VAR14_ACSMLTSMINDEX0VAR14_MASK  0x1fffffU
#define ACSM_ACSMLTSMINDEX0VAR14_ACSMLTSMINDEX0VAR14_SHIFT 0
#define ACSM_ACSMLTSMINDEX0VAR16_ADD    (ACSM_BASE_ADD + 0x158)
#define ACSM_ACSMLTSMINDEX0VAR16_MASK   0xffffffff
#define ACSM_ACSMLTSMINDEX0VAR16_ACSMLTSMINDEX0VAR16_MASK  0x1fffffU
#define ACSM_ACSMLTSMINDEX0VAR16_ACSMLTSMINDEX0VAR16_SHIFT 0
#define ACSM_ACSMLTSMMSK0VAR0_ADD    (ACSM_BASE_ADD + 0x218)
#define ACSM_ACSMLTSMMSK0VAR1_ADD    (ACSM_BASE_ADD + 0x21c)
#define ACSM_ACSMLTSMMSK0VAR2_ADD    (ACSM_BASE_ADD + 0x220)
#define ACSM_ACSMLTSMMSK0VAR3_ADD    (ACSM_BASE_ADD + 0x224)
#define ACSM_ACSMLTSMMSK0VAR4_ADD    (ACSM_BASE_ADD + 0x228)
#define ACSM_ACSMLTSMMSK0VAR4_ADD    (ACSM_BASE_ADD + 0x228)
#define ACSM_ACSMLTSMMSK0VAR5_ADD    (ACSM_BASE_ADD + 0x22c)
#define ACSM_ACSMLTSMMSK0VAR6_ADD    (ACSM_BASE_ADD + 0x230)
#define ACSM_ACSMLTSMMSK0VAR7_ADD    (ACSM_BASE_ADD + 0x234)
#define ACSM_ACSMLTSMMSK0VAR8_ADD    (ACSM_BASE_ADD + 0x238)
#define ACSM_ACSMLTSMMSK0VAR9_ADD    (ACSM_BASE_ADD + 0x23c)
#define ACSM_ACSMLTSMMSK0VAR10_ADD    (ACSM_BASE_ADD + 0x240)
#define ACSM_ACSMLTSMMSK0VAR11_ADD    (ACSM_BASE_ADD + 0x244)
#define ACSM_ACSMLTSMMSK0VAR12_ADD    (ACSM_BASE_ADD + 0x248)
#define ACSM_ACSMLTSMMSK0VAR13_ADD    (ACSM_BASE_ADD + 0x24c)
#define ACSM_ACSMLTSMMSK0VAR14_ADD    (ACSM_BASE_ADD + 0x250)
#define ACSM_ACSMLTSMMSK0VAR15_ADD    (ACSM_BASE_ADD + 0x254)
#define ACSM_ACSMLTSMMSK0VAR16_ADD    (ACSM_BASE_ADD + 0x258)
#define ACSM_ACSMLTSMMSK0VAR17_ADD    (ACSM_BASE_ADD + 0x25c)
#define ACSM_ACSMLTSMMSK0VAR18_ADD    (ACSM_BASE_ADD + 0x260)
#define ACSM_ACSMLTSMMSK0VAR19_ADD    (ACSM_BASE_ADD + 0x264)
#define ACSM_ACSMLTSMMSK0VAR20_ADD    (ACSM_BASE_ADD + 0x268)
#define ACSM_ACSMLTSMMSK0VAR21_ADD    (ACSM_BASE_ADD + 0x26c)
#define ACSM_ACSMLTSMMSK0VAR22_ADD    (ACSM_BASE_ADD + 0x270)
#define ACSM_ACSMLTSMMSK0VAR23_ADD    (ACSM_BASE_ADD + 0x274)
#define ACSM_ACSMLTSMMSK0VAR24_ADD    (ACSM_BASE_ADD + 0x278)
#define ACSM_ACSMLTSMMSK0VAR25_ADD    (ACSM_BASE_ADD + 0x27c)
#define ACSM_ACSMLTSMMSK0VAR26_ADD    (ACSM_BASE_ADD + 0x280)
#define ACSM_ACSMLTSMMSK0VAR27_ADD    (ACSM_BASE_ADD + 0x284)
#define ACSM_ACSMLTSMMSK0VAR28_ADD    (ACSM_BASE_ADD + 0x288)
#define ACSM_ACSMLTSMMSK0VAR29_ADD    (ACSM_BASE_ADD + 0x28c)
#define ACSM_ACSMLTSMMSK0VAR30_ADD    (ACSM_BASE_ADD + 0x290)
#define ACSM_ACSMLTSMMSK1VAR0_ADD    (ACSM_BASE_ADD + 0x298)
#define ACSM_ACSMLTSMMSK1VAR1_ADD    (ACSM_BASE_ADD + 0x29c)
#define ACSM_ACSMLTSMMSK1VAR2_ADD    (ACSM_BASE_ADD + 0x2a0)
#define ACSM_ACSMLTSMMSK1VAR3_ADD    (ACSM_BASE_ADD + 0x2a4)
#define ACSM_ACSMLTSMMSK1VAR4_ADD    (ACSM_BASE_ADD + 0x2a8)
#define ACSM_ACSMLTSMMSK1VAR5_ADD    (ACSM_BASE_ADD + 0x2ac)
#define ACSM_ACSMLTSMMSK1VAR6_ADD    (ACSM_BASE_ADD + 0x2b0)
#define ACSM_ACSMLTSMMSK1VAR7_ADD    (ACSM_BASE_ADD + 0x2b4)
#define ACSM_ACSMLTSMMSK1VAR8_ADD    (ACSM_BASE_ADD + 0x2b8)
#define ACSM_ACSMLTSMMSK1VAR9_ADD    (ACSM_BASE_ADD + 0x2bc)
#define ACSM_ACSMLTSMMSK1VAR10_ADD    (ACSM_BASE_ADD + 0x2c0)
#define ACSM_ACSMLTSMMSK1VAR11_ADD    (ACSM_BASE_ADD + 0x2c4)
#define ACSM_ACSMLTSMMSK1VAR12_ADD    (ACSM_BASE_ADD + 0x2c8)
#define ACSM_ACSMLTSMMSK1VAR13_ADD    (ACSM_BASE_ADD + 0x2cc)
#define ACSM_ACSMLTSMMSK1VAR14_ADD    (ACSM_BASE_ADD + 0x2d0)
#define ACSM_ACSMLTSMMSK1VAR15_ADD    (ACSM_BASE_ADD + 0x2d4)
#define ACSM_ACSMLTSMMSK1VAR16_ADD    (ACSM_BASE_ADD + 0x2d8)
#define ACSM_ACSMLTSMMSK1VAR17_ADD    (ACSM_BASE_ADD + 0x2dc)
#define ACSM_ACSMLTSMMSK1VAR18_ADD    (ACSM_BASE_ADD + 0x2e0)
#define ACSM_ACSMLTSMMSK1VAR19_ADD    (ACSM_BASE_ADD + 0x2e4)
#define ACSM_ACSMLTSMMSK1VAR20_ADD    (ACSM_BASE_ADD + 0x2e8)
#define ACSM_ACSMLTSMMSK1VAR21_ADD    (ACSM_BASE_ADD + 0x2ec)
#define ACSM_ACSMLTSMMSK1VAR22_ADD    (ACSM_BASE_ADD + 0x2f0)
#define ACSM_ACSMLTSMMSK1VAR23_ADD    (ACSM_BASE_ADD + 0x2f4)
#define ACSM_ACSMLTSMMSK1VAR24_ADD    (ACSM_BASE_ADD + 0x2f8)
#define ACSM_ACSMLTSMMSK1VAR25_ADD    (ACSM_BASE_ADD + 0x2fc)
#define ACSM_ACSMLTSMMSK1VAR26_ADD    (ACSM_BASE_ADD + 0x300)
#define ACSM_ACSMLTSMMSK1VAR27_ADD    (ACSM_BASE_ADD + 0x304)
#define ACSM_ACSMLTSMMSK1VAR28_ADD    (ACSM_BASE_ADD + 0x308)
#define ACSM_ACSMLTSMMSK1VAR29_ADD    (ACSM_BASE_ADD + 0x30c)
#define ACSM_ACSMLTSMMSK1VAR30_ADD    (ACSM_BASE_ADD + 0x310)
#define ACSM_ACSMLTSMMSK0VAR21ALT_ADD    (ACSM_BASE_ADD + 0x318)
#define ACSM_ACSMLTSMMSK0VAR22ALT_ADD    (ACSM_BASE_ADD + 0x31c)
#define ACSM_ACSMLTSMMSK0VAR23ALT_ADD    (ACSM_BASE_ADD + 0x320)
#define ACSM_ACSMLTSMMSK0VAR24ALT_ADD    (ACSM_BASE_ADD + 0x324)
#define ACSM_ACSMLTSMMSK0VAR25ALT_ADD    (ACSM_BASE_ADD + 0x328)
#define ACSM_ACSMLTSMMSK0VAR26ALT_ADD    (ACSM_BASE_ADD + 0x32c)
#define ACSM_ACSMLTSMMSK0VAR27ALT_ADD    (ACSM_BASE_ADD + 0x330)
#define ACSM_ACSMLTSMMSK0VAR28ALT_ADD    (ACSM_BASE_ADD + 0x334)
#define ACSM_ACSMLTSMMSK0VAR29ALT_ADD    (ACSM_BASE_ADD + 0x338)
#define ACSM_ACSMLTSMMSK0VAR30ALT_ADD    (ACSM_BASE_ADD + 0x33c)
#define ACSM_ACSMLTSMMSK1VAR21ALT_ADD    (ACSM_BASE_ADD + 0x344)
#define ACSM_ACSMLTSMMSK1VAR22ALT_ADD    (ACSM_BASE_ADD + 0x348)
#define ACSM_ACSMLTSMMSK1VAR23ALT_ADD    (ACSM_BASE_ADD + 0x34c)
#define ACSM_ACSMLTSMMSK1VAR24ALT_ADD    (ACSM_BASE_ADD + 0x350)
#define ACSM_ACSMLTSMMSK1VAR25ALT_ADD    (ACSM_BASE_ADD + 0x354)
#define ACSM_ACSMLTSMMSK1VAR26ALT_ADD    (ACSM_BASE_ADD + 0x358)
#define ACSM_ACSMLTSMMSK1VAR27ALT_ADD    (ACSM_BASE_ADD + 0x35c)
#define ACSM_ACSMLTSMMSK1VAR28ALT_ADD    (ACSM_BASE_ADD + 0x360)
#define ACSM_ACSMLTSMMSK1VAR29ALT_ADD    (ACSM_BASE_ADD + 0x364)
#define ACSM_ACSMLTSMMSK1VAR30ALT_ADD    (ACSM_BASE_ADD + 0x368)

#endif /* RCAR_UCIE_UCIE_PHY_H */
