/*
 *
 * Copyright (c) 2025 Renesas Electronics Corporation
 *
 * SPDX-License-Identifier: MIT
 *
 */

#ifndef RCAR_UCIE_PCIE_CONTROLLER_H
#define RCAR_UCIE_PCIE_CONTROLLER_H


/*-----  Registers Address-Block Base Address  -----*/
#define PF0_TYPE1_HDR_BASE_ADD           RCAR_UCIE_BASE_ADD(0x00000000) // 0x0
#define PF0_PCIE_CAP_BASE_ADD            RCAR_UCIE_BASE_ADD(0x00000070) // 0x70
#define PF0_SPCIE_CAP_BASE_ADD           RCAR_UCIE_BASE_ADD(0x00000148) // 0x148
#define PF0_PL16G_CAP_BASE_ADD           RCAR_UCIE_BASE_ADD(0x00000168) // 0x168
#define PF0_PL32G_CAP_BASE_ADD           RCAR_UCIE_BASE_ADD(0x000001b8) // 0x1b8
#define PF0_PL64G_CAP_BASE_ADD           RCAR_UCIE_BASE_ADD(0x000001e0) // 0x1e0
#define PF0_CXL_2_0_EXT_CAP_BASE_ADD     RCAR_UCIE_BASE_ADD(0x000003d0) // 0x3d0
#define PF0_PORT_LOGIC_BASE_ADD          RCAR_UCIE_BASE_ADD(0x00000700) // 0x700
#define PF0_ATU_CAP_BASE_ADD             RCAR_UCIE_BASE_ADD(0x00300000) // 0x300000
#define PF0_HDMA_CAP_BASE_ADD            RCAR_UCIE_BASE_ADD(0x00380000) // 0x380000
#define PF0_MEMBAR0_RAS_CAP_BASE_ADD     RCAR_UCIE_BASE_ADD(0x00f01050) // 0xf01050

/*-----  PF0_TYPE1_HDR detail register offset  -----*/
#define PF0_TYPE1_HDR_BAR0_REG_ADD    (PF0_TYPE1_HDR_BASE_ADD + 0x10)
#define PF0_TYPE1_HDR_BAR1_REG_ADD    (PF0_TYPE1_HDR_BASE_ADD + 0x14)
#define PF0_TYPE1_HDR_SEC_LAT_TIMER_SUB_BUS_SEC_BUS_PRI_BUS_REG_ADD    (PF0_TYPE1_HDR_BASE_ADD + 0x18)
#define PF0_TYPE1_HDR_SEC_STAT_IO_LIMIT_IO_BASE_REG_ADD       (PF0_TYPE1_HDR_BASE_ADD + 0x1c)
#define PF0_TYPE1_HDR_MEM_LIMIT_MEM_BASE_REG_ADD              (PF0_TYPE1_HDR_BASE_ADD + 0x20)
#define PF0_TYPE1_HDR_PREF_MEM_LIMIT_PREF_MEM_BASE_REG_ADD    (PF0_TYPE1_HDR_BASE_ADD + 0x24)
#define PF0_TYPE1_HDR_PREF_BASE_UPPER_REG_ADD                 (PF0_TYPE1_HDR_BASE_ADD + 0x28)
#define PF0_TYPE1_HDR_PREF_LIMIT_UPPER_REG_ADD                (PF0_TYPE1_HDR_BASE_ADD + 0x2c)
#define PF0_TYPE1_HDR_IO_LIMIT_UPPER_IO_BASE_UPPER_REG_ADD    (PF0_TYPE1_HDR_BASE_ADD + 0x30)

/*-----  PF0_PCIE_CAP detail register offset  -----*/
#define PF0_PCIE_CAP_PCIE_CAP_ID_PCIE_NEXT_CAP_PTR_PCIE_CAP_REG_ADD    (PF0_PCIE_CAP_BASE_ADD + 0x0)
#define PF0_PCIE_CAP_DEVICE_CONTROL_DEVICE_STATUS_ADD                  (PF0_PCIE_CAP_BASE_ADD + 0x8)
#define PF0_PCIE_CAP_LINK_CONTROL2_LINK_STATUS2_REG_ADD                (PF0_PCIE_CAP_BASE_ADD + 0x30)

/*-----  PF0_SPCIE_CAP detail register offset  -----*/
#define PF0_SPCIE_CAP_SPCIE_CAP_OFF_0CH_REG_ADD    (PF0_SPCIE_CAP_BASE_ADD + 0xc)
#define PF0_SPCIE_CAP_SPCIE_CAP_OFF_10H_REG_ADD    (PF0_SPCIE_CAP_BASE_ADD + 0x10)
#define PF0_SPCIE_CAP_SPCIE_CAP_OFF_14H_REG_ADD    (PF0_SPCIE_CAP_BASE_ADD + 0x14)
#define PF0_SPCIE_CAP_SPCIE_CAP_OFF_18H_REG_ADD    (PF0_SPCIE_CAP_BASE_ADD + 0x18)

/*-----  PF0_PL16G_CAP detail register offset  -----*/
#define PF0_PL16G_CAP_PL16G_CAP_OFF_20H_REG_ADD    (PF0_PL16G_CAP_BASE_ADD + 0x20)
#define PF0_PL16G_CAP_PL16G_CAP_OFF_24H_REG_ADD    (PF0_PL16G_CAP_BASE_ADD + 0x24)

/*-----  PF0_PL32G_CAP detail register offset  -----*/
#define PF0_PL32G_CAP_PL32G_CONTROL_REG_ADD        (PF0_PL32G_CAP_BASE_ADD + 0x8)
#define PF0_PL32G_CAP_PL32G_CAP_OFF_20H_REG_ADD    (PF0_PL32G_CAP_BASE_ADD + 0x20)
#define PF0_PL32G_CAP_PL32G_CAP_OFF_24H_REG_ADD    (PF0_PL32G_CAP_BASE_ADD + 0x24)

/*-----  PF0_PL64G_CAP detail register offset  -----*/
#define PF0_PL64G_CAP_PL64G_LANE_EQ_10H_REG_ADD    (PF0_PL64G_CAP_BASE_ADD + 0x10)
#define PF0_PL64G_CAP_PL64G_LANE_EQ_14H_REG_ADD    (PF0_PL64G_CAP_BASE_ADD + 0x14)

/*-----  PF0_CXL_2_0_EXT_CAP detail register offset  -----*/
#define PF0_CXL_2_0_EXT_CAP_CXL_2_0_CTRL_ALT_BUS_BASE_LIMIT_OFF_ADD       (PF0_CXL_2_0_EXT_CAP_BASE_ADD + 0xc)
#define PF0_CXL_2_0_EXT_CAP_CXL_2_0_ALT_MEM_BASE_LIMIT_OFF_ADD            (PF0_CXL_2_0_EXT_CAP_BASE_ADD + 0x10)
#define PF0_CXL_2_0_EXT_CAP_CXL_2_0_ALT_PREFETCH_MEM_BASE_LIMIT_OFF_ADD   (PF0_CXL_2_0_EXT_CAP_BASE_ADD + 0x14)

/*-----  PF0_PORT_LOGIC detail register offset  -----*/
#define PF0_PORT_LOGIC_TRGT_MAP_CTRL_OFF_ADD        (PF0_PORT_LOGIC_BASE_ADD + 0x11c)
#define PF0_PORT_LOGIC_MISC_CONTROL_1_OFF_ADD       (PF0_PORT_LOGIC_BASE_ADD + 0x1bc)
#define PF0_PORT_LOGIC_CXL_VLSM_CSR_REG_OFF_ADD     (PF0_PORT_LOGIC_BASE_ADD + 0x548)

/*-----  PF0_MEMBAR0_RAS_CAP detail register offset  -----*/
#define PF0_MEMBAR0_RAS_CAP_MEMBAR0_RAS_UNCOR_ERROR_MASK_REG_OFF_ADD   (PF0_MEMBAR0_RAS_CAP_BASE_ADD + 0x4)
#define PF0_MEMBAR0_RAS_CAP_MEMBAR0_RAS_CORR_ERROR_MASK_REG_OFF_ADD    (PF0_MEMBAR0_RAS_CAP_BASE_ADD + 0x10)

#endif /* RCAR_UCIE_PCIE_CONTROLLER_H */
