/*
 *
 * Copyright (c) 2026 Renesas Electronics Corporation
 *
 * SPDX-License-Identifier: MIT
 *
 */

/*******************************************************************************
 * DESCRIPTION   : Module Controller register header
 ******************************************************************************/

#ifndef MODULE_CONTROLLER_REGISTER_H_
#define MODULE_CONTROLLER_REGISTER_H_

/* Module Controller register offset address */
#define MDLCNMSRESL_OFFSET      (0x0900U)
#define MDLCNMSRESSL_OFFSET     (0x0960U)
#define MDLCNPKCPROT1_OFFSET    (0x0CF4U)

/* Hier Structure: 16, HSCS */

/* Module System Reset Register [l] for [o], n = 16, l = 00 to 23 */
#define MDLC16MSRES00    (BASE_ADDR_HIER_HSCS + MDLCNMSRESL_OFFSET + 0x00U * 0x4U)
#define MDLC16MSRES01    (BASE_ADDR_HIER_HSCS + MDLCNMSRESL_OFFSET + 0x01U * 0x4U)
#define MDLC16MSRES02    (BASE_ADDR_HIER_HSCS + MDLCNMSRESL_OFFSET + 0x02U * 0x4U)
#define MDLC16MSRES03    (BASE_ADDR_HIER_HSCS + MDLCNMSRESL_OFFSET + 0x03U * 0x4U)
#define MDLC16MSRES04    (BASE_ADDR_HIER_HSCS + MDLCNMSRESL_OFFSET + 0x04U * 0x4U)
#define MDLC16MSRES05    (BASE_ADDR_HIER_HSCS + MDLCNMSRESL_OFFSET + 0x05U * 0x4U)
#define MDLC16MSRES06    (BASE_ADDR_HIER_HSCS + MDLCNMSRESL_OFFSET + 0x06U * 0x4U)
#define MDLC16MSRES07    (BASE_ADDR_HIER_HSCS + MDLCNMSRESL_OFFSET + 0x07U * 0x4U)
#define MDLC16MSRES08    (BASE_ADDR_HIER_HSCS + MDLCNMSRESL_OFFSET + 0x08U * 0x4U)
#define MDLC16MSRES09    (BASE_ADDR_HIER_HSCS + MDLCNMSRESL_OFFSET + 0x09U * 0x4U)
#define MDLC16MSRES10    (BASE_ADDR_HIER_HSCS + MDLCNMSRESL_OFFSET + 0x0AU * 0x4U)
#define MDLC16MSRES11    (BASE_ADDR_HIER_HSCS + MDLCNMSRESL_OFFSET + 0x0BU * 0x4U)
#define MDLC16MSRES12    (BASE_ADDR_HIER_HSCS + MDLCNMSRESL_OFFSET + 0x0CU * 0x4U)
#define MDLC16MSRES13    (BASE_ADDR_HIER_HSCS + MDLCNMSRESL_OFFSET + 0x0DU * 0x4U)
#define MDLC16MSRES14    (BASE_ADDR_HIER_HSCS + MDLCNMSRESL_OFFSET + 0x0EU * 0x4U)
#define MDLC16MSRES15    (BASE_ADDR_HIER_HSCS + MDLCNMSRESL_OFFSET + 0x0FU * 0x4U)
#define MDLC16MSRES16    (BASE_ADDR_HIER_HSCS + MDLCNMSRESL_OFFSET + 0x10U * 0x4U)
#define MDLC16MSRES17    (BASE_ADDR_HIER_HSCS + MDLCNMSRESL_OFFSET + 0x11U * 0x4U)
#define MDLC16MSRES18    (BASE_ADDR_HIER_HSCS + MDLCNMSRESL_OFFSET + 0x12U * 0x4U)
#define MDLC16MSRES19    (BASE_ADDR_HIER_HSCS + MDLCNMSRESL_OFFSET + 0x13U * 0x4U)
#define MDLC16MSRES20    (BASE_ADDR_HIER_HSCS + MDLCNMSRESL_OFFSET + 0x14U * 0x4U)
#define MDLC16MSRES21    (BASE_ADDR_HIER_HSCS + MDLCNMSRESL_OFFSET + 0x15U * 0x4U)

/* Module System Reset Status Register [l] for [o], n = 16, l = 00 to 23 */
#define MDLC16MSRESS00    (BASE_ADDR_HIER_HSCS + MDLCNMSRESSL_OFFSET + 0x00U * 0x4U)
#define MDLC16MSRESS01    (BASE_ADDR_HIER_HSCS + MDLCNMSRESSL_OFFSET + 0x01U * 0x4U)
#define MDLC16MSRESS02    (BASE_ADDR_HIER_HSCS + MDLCNMSRESSL_OFFSET + 0x02U * 0x4U)
#define MDLC16MSRESS03    (BASE_ADDR_HIER_HSCS + MDLCNMSRESSL_OFFSET + 0x03U * 0x4U)
#define MDLC16MSRESS04    (BASE_ADDR_HIER_HSCS + MDLCNMSRESSL_OFFSET + 0x04U * 0x4U)
#define MDLC16MSRESS05    (BASE_ADDR_HIER_HSCS + MDLCNMSRESSL_OFFSET + 0x05U * 0x4U)
#define MDLC16MSRESS06    (BASE_ADDR_HIER_HSCS + MDLCNMSRESSL_OFFSET + 0x06U * 0x4U)
#define MDLC16MSRESS07    (BASE_ADDR_HIER_HSCS + MDLCNMSRESSL_OFFSET + 0x07U * 0x4U)
#define MDLC16MSRESS08    (BASE_ADDR_HIER_HSCS + MDLCNMSRESSL_OFFSET + 0x08U * 0x4U)
#define MDLC16MSRESS09    (BASE_ADDR_HIER_HSCS + MDLCNMSRESSL_OFFSET + 0x09U * 0x4U)
#define MDLC16MSRESS10    (BASE_ADDR_HIER_HSCS + MDLCNMSRESSL_OFFSET + 0x0AU * 0x4U)
#define MDLC16MSRESS11    (BASE_ADDR_HIER_HSCS + MDLCNMSRESSL_OFFSET + 0x0BU * 0x4U)
#define MDLC16MSRESS12    (BASE_ADDR_HIER_HSCS + MDLCNMSRESSL_OFFSET + 0x0CU * 0x4U)
#define MDLC16MSRESS13    (BASE_ADDR_HIER_HSCS + MDLCNMSRESSL_OFFSET + 0x0DU * 0x4U)
#define MDLC16MSRESS14    (BASE_ADDR_HIER_HSCS + MDLCNMSRESSL_OFFSET + 0x0EU * 0x4U)
#define MDLC16MSRESS15    (BASE_ADDR_HIER_HSCS + MDLCNMSRESSL_OFFSET + 0x0FU * 0x4U)
#define MDLC16MSRESS16    (BASE_ADDR_HIER_HSCS + MDLCNMSRESSL_OFFSET + 0x10U * 0x4U)
#define MDLC16MSRESS17    (BASE_ADDR_HIER_HSCS + MDLCNMSRESSL_OFFSET + 0x11U * 0x4U)
#define MDLC16MSRESS18    (BASE_ADDR_HIER_HSCS + MDLCNMSRESSL_OFFSET + 0x12U * 0x4U)
#define MDLC16MSRESS19    (BASE_ADDR_HIER_HSCS + MDLCNMSRESSL_OFFSET + 0x13U * 0x4U)
#define MDLC16MSRESS20    (BASE_ADDR_HIER_HSCS + MDLCNMSRESSL_OFFSET + 0x14U * 0x4U)
#define MDLC16MSRESS21    (BASE_ADDR_HIER_HSCS + MDLCNMSRESSL_OFFSET + 0x15U * 0x4U)

/* Module Controller Register 1 Key Code Protection Register for [o], n = 16 */
#define MDLC16PKCPROT1  (BASE_ADDR_HIER_HSCS + MDLCNPKCPROT1_OFFSET)

#endif /* MODULE_CONTROLLER_REGISTER_H_ */

