/*
 * Copyright (c) 2026 Renesas Electronics Corporation
 *
 * SPDX-License-Identifier: MIT
 *
 */

/**
 * @defgroup PFC_PRIVATE PFC PRIVATE
 * @{
 * @brief PFC X5H platform.
 *
 */

#ifndef R_PFC_PRVIATE_H
#define R_PFC_PRIVATE_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include "r_pfc_common_private.h"

/* PFC base adrress */
#define PFC_BASE_OFFSET    0x000U
#define PFC_GR_NUM  11

#define PFC_GR_0           (0xC1080000U + PFC_BASE_OFFSET)
#define PFC_GR_1           (0xC1080800U + PFC_BASE_OFFSET)
#define PFC_GR_2           (0xC1081000U + PFC_BASE_OFFSET)
#define PFC_GR_3           (0xC0800000U + PFC_BASE_OFFSET)
#define PFC_GR_4           (0xC0800800U + PFC_BASE_OFFSET)
#define PFC_GR_5           (0xC0400000U + PFC_BASE_OFFSET)
#define PFC_GR_6           (0xC0400800U + PFC_BASE_OFFSET)
#define PFC_GR_7           (0xC0401000U + PFC_BASE_OFFSET)
#define PFC_GR_8           (0xC0401800U + PFC_BASE_OFFSET)
#define PFC_GR_9           (0xC9B00000U + PFC_BASE_OFFSET)
#define PFC_GR_10          (0xC9B00800U + PFC_BASE_OFFSET)

static const uint32_t pfc_gr_base[PFC_GR_NUM] =
{
    PFC_GR_0,
    PFC_GR_1,
    PFC_GR_2,
    PFC_GR_3,
    PFC_GR_4,
    PFC_GR_5,
    PFC_GR_6,
    PFC_GR_7,
    PFC_GR_8,
    PFC_GR_9,
    PFC_GR_10
};

#define HTX0                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_05, RCAR_PFC_PIN_00, RCAR_PFC_FUNC_0)
#define HRX0                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_05, RCAR_PFC_PIN_01, RCAR_PFC_FUNC_0)
#define HRTS0_N             GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_05, RCAR_PFC_PIN_02, RCAR_PFC_FUNC_0)
#define HCTS0_N             GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_05, RCAR_PFC_PIN_03, RCAR_PFC_FUNC_0)
#define HSCK0               GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_05, RCAR_PFC_PIN_04, RCAR_PFC_FUNC_0)
CREATE_GROUP(hscif0_grp, HTX0, HRX0, HRTS0_N, HCTS0_N, HSCK0)

#define TX0                 GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_05, RCAR_PFC_PIN_00, RCAR_PFC_FUNC_1)
#define RX0                 GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_05, RCAR_PFC_PIN_01, RCAR_PFC_FUNC_1)
#define RTS0_N              GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_05, RCAR_PFC_PIN_02, RCAR_PFC_FUNC_1)
#define CTS0_N              GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_05, RCAR_PFC_PIN_03, RCAR_PFC_FUNC_1)
#define SCK0                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_05, RCAR_PFC_PIN_04, RCAR_PFC_FUNC_1)
#define SCIF_CLK            GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_05, RCAR_PFC_PIN_05, RCAR_PFC_FUNC_0)
CREATE_GROUP(scif0_grp, TX0, RX0, RTS0_N, CTS0_N, SCK0, SCIF_CLK)

#define HTX1                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_05, RCAR_PFC_PIN_06, RCAR_PFC_FUNC_0)
#define HRX1                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_05, RCAR_PFC_PIN_07, RCAR_PFC_FUNC_0)
#define HRTS1_N             GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_05, RCAR_PFC_PIN_08, RCAR_PFC_FUNC_0)
#define HCTS1_N             GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_05, RCAR_PFC_PIN_09, RCAR_PFC_FUNC_0)
#define HSCK1               GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_05, RCAR_PFC_PIN_10, RCAR_PFC_FUNC_0)
CREATE_GROUP(hscif1_grp, HTX1, HRX1, HRTS1_N, HCTS1_N, HSCK1)

#define TX1                 GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_05, RCAR_PFC_PIN_06, RCAR_PFC_FUNC_1)
#define RX1                 GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_05, RCAR_PFC_PIN_07, RCAR_PFC_FUNC_1)
#define RTS1_N              GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_05, RCAR_PFC_PIN_08, RCAR_PFC_FUNC_1)
#define CTS1_N              GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_05, RCAR_PFC_PIN_09, RCAR_PFC_FUNC_1)
#define SCK1                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_05, RCAR_PFC_PIN_10, RCAR_PFC_FUNC_1)
CREATE_GROUP(scif1_grp, TX1, RX1, RTS1_N, CTS1_N, SCK1)

#define HTX2                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_04, RCAR_PFC_FUNC_1)
#define HRX2                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_05, RCAR_PFC_FUNC_1)
#define HRTS2_N             GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_06, RCAR_PFC_FUNC_1)
#define HCTS2_N             GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_07, RCAR_PFC_FUNC_1)
#define HSCK2               GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_03, RCAR_PFC_FUNC_1)
CREATE_GROUP(hscif2_grp, HTX2, HRX2, HRTS2_N, HCTS2_N, HSCK2)

#define HTX3                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_06, RCAR_PFC_PIN_17, RCAR_PFC_FUNC_2)
#define HRX3                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_06, RCAR_PFC_PIN_18, RCAR_PFC_FUNC_2)
#define HRTS3_N             GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_06, RCAR_PFC_PIN_22, RCAR_PFC_FUNC_2)
#define HCTS3_N             GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_06, RCAR_PFC_PIN_23, RCAR_PFC_FUNC_2)
#define HSCK3               GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_06, RCAR_PFC_PIN_21, RCAR_PFC_FUNC_2)
CREATE_GROUP(hscif3_grp, HTX3, HRX3, HRTS3_N, HCTS3_N, HSCK3)

#define TX3                 GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_06, RCAR_PFC_PIN_17, RCAR_PFC_FUNC_3)
#define RX3                 GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_06, RCAR_PFC_PIN_18, RCAR_PFC_FUNC_3)
#define RTS3_N              GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_06, RCAR_PFC_PIN_22, RCAR_PFC_FUNC_3)
#define CTS3_N              GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_06, RCAR_PFC_PIN_23, RCAR_PFC_FUNC_3)
#define SCK3                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_06, RCAR_PFC_PIN_21, RCAR_PFC_FUNC_3)
CREATE_GROUP(scif3_grp, TX3, RX3, RTS3_N, CTS3_N, SCK3)

#define TX4                 GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_04, RCAR_PFC_FUNC_2)
#define RX4                 GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_05, RCAR_PFC_FUNC_2)
#define RTS4_N              GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_06, RCAR_PFC_FUNC_2)
#define CTS4_N              GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_07, RCAR_PFC_FUNC_2)
#define SCK4                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_03, RCAR_PFC_FUNC_2)
CREATE_GROUP(scif4_grp, TX4, RX4, RTS4_N, CTS4_N, SCK4)

#define SDA0                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_02, RCAR_PFC_PIN_20, RCAR_PFC_FUNC_0)
#define SCL0                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_02, RCAR_PFC_PIN_19, RCAR_PFC_FUNC_0)
#define MODSEL_SDA0         GEN_ID(REG_MODSEL, RCAR_PFC_GROUP_02, RCAR_PFC_PIN_20, MODSEL_I2C_MODE)
#define MODSEL_SCL0         GEN_ID(REG_MODSEL, RCAR_PFC_GROUP_02, RCAR_PFC_PIN_19, MODSEL_I2C_MODE)
CREATE_GROUP(i2c0_grp, SDA0, SCL0, MODSEL_SDA0, MODSEL_SCL0)

#define SDA1                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_01, RCAR_PFC_FUNC_0)
#define SCL1                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_00, RCAR_PFC_FUNC_0)
#define MODSEL_SDA1         GEN_ID(REG_MODSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_01, MODSEL_I2C_MODE)
#define MODSEL_SCL1         GEN_ID(REG_MODSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_00, MODSEL_I2C_MODE)
CREATE_GROUP(i2c1_grp, SDA1, SCL1, MODSEL_SDA1, MODSEL_SCL1)

#define SDA2                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_03, RCAR_PFC_FUNC_0)
#define SCL2                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_02, RCAR_PFC_FUNC_0)
#define MODSEL_SDA2         GEN_ID(REG_MODSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_03, MODSEL_I2C_MODE)
#define MODSEL_SCL2         GEN_ID(REG_MODSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_02, MODSEL_I2C_MODE)
CREATE_GROUP(i2c2_grp, SDA2, SCL2, MODSEL_SDA2, MODSEL_SCL2)

#define SDA3                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_05, RCAR_PFC_FUNC_0)
#define SCL3                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_04, RCAR_PFC_FUNC_0)
#define MODSEL_SDA3         GEN_ID(REG_MODSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_05, MODSEL_I2C_MODE)
#define MODSEL_SCL3         GEN_ID(REG_MODSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_04, MODSEL_I2C_MODE)
CREATE_GROUP(i2c3_grp, SDA3, SCL3, MODSEL_SDA3, MODSEL_SCL3)

#define SDA4                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_07, RCAR_PFC_FUNC_0)
#define SCL4                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_06, RCAR_PFC_FUNC_0)
#define MODSEL_SDA4         GEN_ID(REG_MODSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_07, MODSEL_I2C_MODE)
#define MODSEL_SCL4         GEN_ID(REG_MODSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_06, MODSEL_I2C_MODE)
CREATE_GROUP(i2c4_grp, SDA4, SCL4, MODSEL_SDA4, MODSEL_SCL4)

#define SDA5                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_09, RCAR_PFC_FUNC_0)
#define SCL5                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_08, RCAR_PFC_FUNC_0)
#define MODSEL_SDA5         GEN_ID(REG_MODSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_09, MODSEL_I2C_MODE)
#define MODSEL_SCL5         GEN_ID(REG_MODSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_08, MODSEL_I2C_MODE)
CREATE_GROUP(i2c5_grp, SDA5, SCL5, MODSEL_SDA5, MODSEL_SCL5)

#define SDA6                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_11, RCAR_PFC_FUNC_0)
#define SCL6                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_10, RCAR_PFC_FUNC_0)
#define MODSEL_SDA6         GEN_ID(REG_MODSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_11, MODSEL_I2C_MODE)
#define MODSEL_SCL6         GEN_ID(REG_MODSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_10, MODSEL_I2C_MODE)
CREATE_GROUP(i2c6_grp, SDA6, SCL6, MODSEL_SDA6, MODSEL_SCL6)

#define SDA7                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_13, RCAR_PFC_FUNC_0)
#define SCL7                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_12, RCAR_PFC_FUNC_0)
#define MODSEL_SDA7         GEN_ID(REG_MODSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_13, MODSEL_I2C_MODE)
#define MODSEL_SCL7         GEN_ID(REG_MODSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_12, MODSEL_I2C_MODE)
CREATE_GROUP(i2c7_grp, SDA7, SCL7, MODSEL_SDA7, MODSEL_SCL7)

#define SDA8                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_15, RCAR_PFC_FUNC_0)
#define SCL8                GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_14, RCAR_PFC_FUNC_0)
#define MODSEL_SDA8         GEN_ID(REG_MODSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_15, MODSEL_I2C_MODE)
#define MODSEL_SCL8         GEN_ID(REG_MODSEL, RCAR_PFC_GROUP_08, RCAR_PFC_PIN_14, MODSEL_I2C_MODE)
CREATE_GROUP(i2c8_grp, SDA8, SCL8, MODSEL_SDA8, MODSEL_SCL8)

#define AUDIO_CLKA          GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_07, RCAR_PFC_PIN_08, RCAR_PFC_FUNC_0)
#define AUDIO0_CLKOUT0      GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_06, RCAR_PFC_PIN_19, RCAR_PFC_FUNC_0)
#define SSI5_SCK            GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_07, RCAR_PFC_PIN_09, RCAR_PFC_FUNC_0)
#define SSI5_WS             GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_07, RCAR_PFC_PIN_10, RCAR_PFC_FUNC_0)
#define SSI5_SD             GEN_ID(REG_ALTSEL, RCAR_PFC_GROUP_07, RCAR_PFC_PIN_11, RCAR_PFC_FUNC_0)
CREATE_GROUP(audio0_grp, AUDIO_CLKA, AUDIO0_CLKOUT0, SSI5_SCK, SSI5_WS, SSI5_SD)

static const st_driver_group_t all_drv_groups[] = {
    {MODULE_HSCIF0,  ADD_GROUP(hscif0_grp)},
    {MODULE_HSCIF1,  ADD_GROUP(hscif1_grp)},
    {MODULE_HSCIF2,  ADD_GROUP(hscif2_grp)},
    {MODULE_HSCIF3,  ADD_GROUP(hscif3_grp)},
    {MODULE_SCIF0,   ADD_GROUP(scif0_grp)},
    {MODULE_SCIF1,   ADD_GROUP(scif1_grp)},
    {MODULE_SCIF3,   ADD_GROUP(scif3_grp)},
    {MODULE_SCIF4,   ADD_GROUP(scif4_grp)},
    {MODULE_I2C0,    ADD_GROUP(i2c0_grp)},
    {MODULE_I2C1,    ADD_GROUP(i2c1_grp)},
    {MODULE_I2C2,    ADD_GROUP(i2c2_grp)},
    {MODULE_I2C3,    ADD_GROUP(i2c3_grp)},
    {MODULE_I2C4,    ADD_GROUP(i2c4_grp)},
    {MODULE_I2C5,    ADD_GROUP(i2c5_grp)},
    {MODULE_I2C6,    ADD_GROUP(i2c6_grp)},
    {MODULE_I2C7,    ADD_GROUP(i2c7_grp)},
    {MODULE_I2C8,    ADD_GROUP(i2c8_grp)},
    {MODULE_AUDIO_0, ADD_GROUP(audio0_grp)},
    // Add driver groups.
    {MODULE_INVALID, 0},
};

#ifdef __cplusplus
}
#endif

#endif /* R_PFC_PRIVATE_H */
